/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SandboxFileMount
 */
export interface SandboxFileMount {
  /**
   * The uploaded file ID to mount
   * @type {string}
   * @memberof SandboxFileMount
   */
    'fileId': string;
  /**
   * Absolute target path in sandbox
   * @type {string}
   * @memberof SandboxFileMount
   */
    'targetPath': string;
  /**
   * Mount access mode
   * @type {string}
   * @memberof SandboxFileMount
   */
    'access'?: SandboxFileMountAccessEnum;
}

export const SandboxFileMountAccessEnum = {
    ReadOnly: 'read_only',
    ReadWrite: 'read_write'
} as const;

export type SandboxFileMountAccessEnum = typeof SandboxFileMountAccessEnum[keyof typeof SandboxFileMountAccessEnum];
